
import { GoogleGenAI } from "@google/genai";

interface GenerateMockupsParams {
  image: string;
  mimeType: string;
  category: string;
  prompt: string;
  count: number;
}

const getApiKey = (): string => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API_KEY environment variable not set.");
  }
  return apiKey;
};

async function generateSingleMockup({ image, mimeType, category, prompt }: Omit<GenerateMockupsParams, 'count'>): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });

  const textPrompt = `Create a high-quality, photorealistic mockup. The user's uploaded image should be placed naturally onto a "${category}". The overall style should be: "${prompt || 'clean and modern'}". The background should be simple and not distracting. Ensure the final image is just the mockup, with no additional text or explanations.`;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: image,
            mimeType: mimeType,
          },
        },
        {
          text: textPrompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      }
    }
  });

  if (response.candidates && response.candidates[0].content.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
  }

  throw new Error("No image was generated by the API.");
}

export async function generateMockups({ image, mimeType, category, prompt, count }: GenerateMockupsParams): Promise<string[]> {
  const generationPromises: Promise<string>[] = [];

  for (let i = 0; i < count; i++) {
    generationPromises.push(generateSingleMockup({ image, mimeType, category, prompt }));
  }

  try {
    const results = await Promise.all(generationPromises);
    return results;
  } catch (error) {
    console.error("Error generating mockups:", error);
    throw new Error("One or more mockup generations failed.");
  }
}
